### ISSUE TITLE
Map not showing completely in Shiny

### ISSUE THREAD

**Issue by dkahle** [dkahle/ggmap#234]
I have a new problem this week with ggmap not fully showing up (see screenshot). It would display the top of map and then stop. This problem has only occurred this week as code ran fine last week. I have tried to refresh the app but same problem - map will only show the tip and no more. 

I would appreciate any help. Please? Thanks in advance

![image](https://user-images.githubusercontent.com/43421932/46828057-b8bf6500-cdf6-11e8-9dd4-7d480360c2a3.png)

_Originally posted by @statshermit in https://github.com/dkahle/ggmap/issues/51#issuecomment-429084096_

**Comment by dkahle** [comment]
@statshermit I've seen these kinds of issues show up before when trying to load Stamen maps that were cached empty.  Have you tried forcing the (re-)downloads?

**Comment by statshermit** [comment]
How do I force the (re-)downloads?

Thanks @dkahle

**Comment by dkahle** [comment]
Set `force = TRUE`.

**Comment by statshermit** [comment]
I use ggmap(XX,force=TRUE) but no it's still not showing map to its full extent. It runs ok if I plot as a single map but not as part of shiny app.

**Comment by statshermit** [comment]
I end up going back through and updating almost every library just to be sure since we had problem with ggplot2 latest update a few weeks ago (https://github.com/dkahle/ggmap/issues/51). I use ggigraph in my shiny app which prompts me to think I might have to update this library as well. 

It has basically fixed my problem! (finger crossed until a few new surprises from other libs)
Thanks for your quick response and troubleshooting assistance you put up  :)

**Comment by dkahle** [comment]
Glad to hear it's fixed!

BTW, with `force = true`, I meant as arguments to, e.g., `get_stamenmap()`.

Let me know if this isn't fixed and I'll reopen.
