### ISSUE TITLE
Registering API key only works when package is loaded

### ISSUE THREAD

**Issue by lorenzwalthert** [dkahle/ggmap#244]
```r
ggmap::register_google(key = "my-key-here")
ggmap::get_map()
#> Error in if (has_google_client() && has_google_signature()) { : 
  missing value where TRUE/FALSE needed
```
My problem is that I'd like to use the key in another (internal) package and I don't want people to enter the key all the time, so I must put a library call into it into `.onload()`. 
```r
  library(ggmap)
  register_google(key = "my-key-here")
```
But I don't want ggplot and ggmap loaded automatically.

**Comment by dkahle** [comment]
Hi @lorenzwalthert - sorry to take so long to address this. This should be fixed with this dev commit (0c68d5c). At very least, your code now works. Using `ggmap::register_google()` is probably not really needed anymore, though, as you probably have your key in `.Renviron`. In any case, I'll close for now; let me know if I need to reopen. Thanks!
