### ISSUE TITLE
HTTP Bad request - Can't load a Seattle map

### ISSUE THREAD

**Issue by akshayreddykotha** [dkahle/ggmap#265]
`p <- ggmap(get_googlemap(center = c(lon = -122.335167, lat = 47.608013),
                    zoom = 11, scale = 2,
                    maptype ='terrain',
                    color = 'color'))`

### This is what I get:
Source : https://maps.googleapis.com/maps/api/staticmap?center=47.608013,-122.335167&zoom=11&size=640x640&scale=2&maptype=terrain&key=xxx-qHQcaH6MGoQx2aMs
HTTP 400 Bad Request

This issue was filed on suggestion by @lgellis

**Comment by dkahle** [comment]
Hi @akshayreddykotha – Thanks for the note. 

The URL you posted contains `xxx` along with, it looks like, part of the API key. I assume that __ggmap__ itself produced the `xxx`. (In general, be careful not to share your API key.) At one point in the past the regular expression used to capture keys was not correct and would produce a result like this, and I have since fixed it (I think!).  Since I don't know what version (more specifically commit) you're using, I don't know if you got that fix or not.  To be sure, please reinstall with:
```r
if (!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap")
```
Restart R, reload ggmap, re-register key, and try again. Let me know how that goes.

If it doesn't work, my next step would be to run `ggmap::ggmap_show_api_key()`, re-run the code you tried, and copy/paste the resulting URL into your web browser. If it doesn't work there, your Google setup is not working properly, so we'll have to look into that. (E.g. did you enable the APIs, input billing, etc.) 

Hope that helps! Please do check back.

**Comment by akshayreddykotha** [comment]
Hello David,

Thanks for responding so promptly.

My previous installation snippet was 

```r
if (!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup", force = TRUE)
```

force = TRUE was used to re-do installation again and again for re-usability in environments where packages are already installed.

Also, I changed the key. My earlier key had a hypen amidst, so it produced a part of the key after xxx. But the new key has no hyphen and it still gives the same line shared earlier with only xxx.

Executed  `ggmap::ggmap_show_api_key()` and I got this: ```ggmap will now display PRIVATE api keys in the console.``` and didn't get any URL.

This is what I get by running the HTTP Bad Request 400 URL.
![image](https://user-images.githubusercontent.com/28220296/52472465-6847f080-2bb9-11e9-9c15-c7d33b6d6976.png)

**Comment by dkahle** [comment]
Hi @akshayreddykotha – Sounds like you may need to re-install. Don't do the `ref = "tidyup"`; you can even install from CRAN if you'd like `install.packages("ggmap")` (although, a bug found in `mapdist()` post-versioning, `devtools::install_github("dkahle/ggmap")` is preferable).

When I indicated you should use `ggmap_show_api_key()`, I meant that you should run that function, and then try to get a map (or geocode, or whatever). When you run that second action, a URL will be printed, and that's what we want to look at; that's what you'll want to put into a browser.

**Comment by akshayreddykotha** [comment]
Hi @dkahle  - Do you mean run the ggmap_show_api_key() instead of get_googlemap() function used in the start of this issue?

Could you please share any documentation on `ggmap_show_api_key()`?

I think I got the map in the background when I ran individual R cells but I am not sure if it is reproducible. Also, I didn't get the map loaded when I Knitted my RMD document into the default html format. `output: html_document`.

**Comment by dkahle** [comment]
Hi @akshayreddykotha – `?ggmap_show_api_key` opens the documentation to that function.  The reason I wanted you to turn that on was so that when `get_googlemap()` is called, by default it will put `key=xxx` in the API call instead of `key=[whatever your key is]`.  When you have the latter, you can copy/paste the URL into a web browser to determine if your API key is working.

In any event, looks like you've got it figured out!  Let me know if that's not the case and I'll reopen.  Thanks!

**Comment by akshayreddykotha** [comment]
I ran the function before querying the map. I got the URL with my private api key. When I pasted that URL in the browser, I can't see the map. I just see the image shared in one of my above comments. I would say usage of this package is uncertain. Sometimes the map loads within my RMD file, sometimes it doesn't.

Additionally, I never got the map loaded when I Knitted my RMD document into the default html format. `output: html_document`. I am looking forward for this case as I want to host my work on a web page via bookdown or similar kinds.
