### ISSUE TITLE
Error while loading package ggmap

### ISSUE THREAD

**Issue by umairtariq260** [dkahle/ggmap#268]
Hi
I have just installed the latest version of R and R Studio. Later on i have installed the ggplot2 and ggmap.
While, ggplot2 have been successfully installed, i am receiving the below error once i try to load the ggmap package.

Versions:
R Version 3.5.2
ggplot2 version - 3.1.0

Will appreciate if someone can guide me to the solution here. Thank you

Error received:
> library("ggmap")
Error: package or namespace load failed for ‘ggmap’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘bindrcpp’

Regards

**Comment by umairtariq260** [comment]
Hi
I have used the below command to install ggmap
From Github: devtools::install_github("dkahle/ggmap")

Regards

**Comment by dkahle** [comment]
Hi @umairtariq260 – You have two options, you can either:

1. Install from CRAN, using `install.packages("ggmap")`, in which case CRAN will manage all the dependencies for you (i.e. you won't need to do anything else), or
2. Install from GitHub, which you tried to do. If you go this route, there will be other dependencies that you'll need that `install_github()` won't detect.  In this case, it looks like you need the __bindrcpp__ package, so try `install.packages("bindrcpp")`, then try to install __ggmap__ from GitHub again.

The second approach above has the added advantage of some bug fixes since the last release, but the former is a bit easier. Hope that helps! Check back if it doesn't.

**Comment by umairtariq260** [comment]
Hi @dkahle 
Thanks. I tried option 2 and it works. 

Regards

**Comment by nahin29** [comment]
it's not work. please help

**Comment by Fyasmin05** [comment]
Hi, I installed the ggmap from CRAN and loaded too. But when I tried to do something like this **https://www.r-bloggers.com/r-beginners-plotting-locations-on-to-a-world-map/** it says me to generate an API key. So, I did that and tried to save my API key. But it was telling me that it's an invalid API. I don't know what was wrong. So, I uninstall the ggmap and installed it again from Github. But I faced problem here as well. It was showing me this error -- Error: Failed to install 'ggmap' from GitHub: (converted from warning) cannot remove prior installation of package ‘digest’.
Could you please help in this regard?
