### ISSUE TITLE
geocoding address containing # fails because # is not encoded

### ISSUE THREAD

**Issue by aaronrudkin** [dkahle/ggmap#272]
A colleague of mine was attempting to bulk geocode Twitter data via the `geocode` function. It mostly works, but there are character encoding issues. Here is a reprex:

```
> geocode("Bunche Hall, UCLA, Los Angeles, California #test")

Source : https://maps.googleapis.com/maps/api/geocode/json?address=Bunche+Hall,+UCLA,+Los+Angeles,+California+#test&key=xxx-tjz-c5s
Warning: Geocoding "Bunche Hall, UCLA..." failed with error:
You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account
```

The error was unexpected, but actually makes sense in hindsight. because # is not encoded, the browser sends the GET request with the # intact, the request disregards everything after the # and the API key is never sent, hence the error.

A related but different problem is that geocode requests with properly encoded but illegal characters (including, say, newlines) fail. This is a less urgent problem because the error returned indicates the cause being illegal characters, but it may be smart to filter any illegal characters in advance of running the geocode and message/warn the user if the result changes the text.

**Comment by dkahle** [comment]
Got it, thanks!

As far as the new lines, I'll just leave those in for now since it's kind of strange case where someone is trying to geocode (or use one of the other functions) on new lines. Presumably they'd miss them in a large query, but in general I'd try not to get into whack-a-mole special cases. Especially if __httr__'s picking them up. :)
