### ISSUE TITLE
get_googlemap: 'style' argument produces invalid style specifications in request URL

### ISSUE THREAD

**Issue by coxchristopher** [dkahle/ggmap#30]
Hi,

It seems that there might be an issue with how ggmap parses 'style' arguments to 'get_googlemap'.  At the moment, on line 255 of 'get_googlemap.R', the 'style' argument is prefixed with 'style=' before being added to the URL for the request to Google Maps:

```
style_url <- if(!missing(style)){ paste("style=", style) } else { "" }
```

Unfortunately, 'paste' inserts an additional space (%20) between 'style=' and the 'style' argument, which causes Google to ignore the given styling information.  To fix this, all that's needed is to specify an empty separator in 'paste':

```
style_url <- if(!missing(style)){ paste("style=", style, sep="") } else { "" }
```

Included below is an example, showing the 'style' argument being used to leave out the labels on a Google Maps terrain map.  Without the above change, the current version of ggmap returns a map with the styling information ignored and all of the text labels still visible:

```
library(ggplot2)
library(ggmap)

# Suppress text labels on Google Maps terrain maps.
map.nolabels = get_googlemap(center = c(lon = -106.5813, lat = 52.47975), zoom = 10, maptype = 'terrain', style = 'feature:all|element:labels|visibility:off')
ggmap(map.nolabels, extent = 'device')
```

I hope this helps, but if any other information is needed to reproduce this issue, please let me know, and I would be glad to do what I can.
- Chris

**Comment by mattmoehr** [comment]
And a related problem is that `style` really should be a list or a character vector because multiple styles can be applied a single request but each one needs its own `&style=` param. However, if this bug is fixed, then at least users could hack up their own string concatenation functions to get the second, third, ... etc. occurrences of `&style=` stuck into the string which is passed to the function.
