### ISSUE TITLE
Orphaned on CARN?

### ISSUE THREAD

**Issue by dblodgett-usgs** [dkahle/ggmap#311]
I use ggmap in one of my vignettes. 

Seeing:
```
* checking package dependencies ... NOTE
Suggests orphaned package: 'ggmap'
```

Looks like an install error on Windows. https://cran.r-project.org/web/checks/check_results_ggmap.html

I'd rather not remove my suggest dependency. Are you working on that or... ?

**Comment by dkahle** [comment]
Hm, that's strange. I'll get in contact with them. Thanks!

**Comment by dkahle** [comment]
Actually, are you still getting this issue? After you posted the other day I accessed from my phone and it looked like there were issues, but I don't see them anymore.

**Comment by dblodgett-usgs** [comment]
Yeah -- just did a check `--as-cran` and got the same thing.

**Comment by dkahle** [comment]
Thanks for checking that, I'll send them a note.

**Comment by dblodgett-usgs** [comment]
Still listed as Orphaned... see upper right here: https://www.r-pkg.org/pkg/ggmap

**Comment by dkahle** [comment]
FYI, just followed up with CRAN, hope to get resolved soon.

**Comment by peterdesmet** [comment]
Just stumbled upon this issue, trying to debug a [GitHub action](https://github.com/adokter/bioRad/pull/427/checks?check_run_id=2527568114) running `R-CMD-check` on Windows, which warns (and therefore fails) because of:

```
> checking package dependencies ... WARNING
  Requires orphaned package: 'ggmap'
```

Other users have [reported this before](https://community.rstudio.com/t/orphaned-package-on-windows-build/84165), with the solution to move `ggmap` from `Depends` to `Suggests`, but my package relies on `ggmap`. Reading this issue, it seems like it is caused by 3.0.0 still being marked as ORPHANED on https://www.r-pkg.org/pkg/ggmap.

Any progress in resolving this with CRAN? 🙏
