### ISSUE TITLE
Region support

### ISSUE THREAD

**Issue by kartiek** [dkahle/ggmap#91]
I think, in `geocode`, it would be nice if we can specify the `region` parameter that Google API supports to get region specific results. Now, when ever I want to get the region specific results, I paste `&region=in` to the end of the query (to get India specific information). But many do not know that the results one gets is influenced by the location the query is sent from. So it would be a nice feature to add.

More info here: https://developers.google.com/maps/documentation/geocoding/intro#RegionCodes

**Comment by dkahle** [comment]
I think the best way to do this is to inject it into the URL. (Although I had previously implemented something similar in `get_googlemap()`.) I've gone through each of the Google functions and added an inject parameter so that you can do this kind of thing.  Here, you'd just put `inject = "region=in"`. Thanks!
